name: Publish NuGet Package

on:
  # Triggers the workflow when a release is published
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
