name: Publish NuGet Package

on:
  # Triggers the workflow when a release is published
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
      
    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore
      
    # Build the project
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    # Run tests
    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    # Pack the project into a NuGet package
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkg /p:Version=$(git describe --tags --abbrev=0)
      
    # Publish the NuGet package
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
